//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;


namespace M3U8downloader
{
	public class FileHelper
	{
		public FileHelper ()
		{
		}

		public static void DeleteDirectory (string target_dir)
		{
			string[] files = Directory.GetFiles (target_dir);
			string[] dirs = Directory.GetDirectories (target_dir);
			
			foreach (string file in files) {
				File.SetAttributes (file, FileAttributes.Normal);
				File.Delete (file);
			}
			
			foreach (string dir in dirs) {
				DeleteDirectory (dir);
			}
			
			Directory.Delete (target_dir, false);
		}
	}
}

