//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;


namespace M3U8downloader
{
	public class NetworkHelper
	{
		public NetworkHelper ()
		{
		}

		public static void CopyTo(Stream source, Stream destination)
		{
			// TODO: Argument validation
			byte[] buffer = new byte[16384]; // For example...
			int bytesRead;
			while ((bytesRead = source.Read(buffer, 0, buffer.Length)) > 0)
			{
				destination.Write(buffer, 0, bytesRead);
			}
		}
	}
}

